#!/bin/bash
echo "============================================="
echo "           SAMPLE TERMINAL OUTPUT"
echo "============================================="
echo ""
echo "MANA Boosted - Terminal Screenshot Sample"
echo ""
echo "This is sample text that can be easily captured"
echo "with the Print Screen key."
echo ""
echo "███████████████████████████████████████████"
echo "█                                       █"
echo "█          MANA    BOOSTED              █"
echo "█                                       █"
echo "███████████████████████████████████████████"
echo ""
echo "Current Time: $(date)"
echo "System: $(uname -s)"
echo "Processor: $(uname -p)"
echo "Terminal: $TERM"
echo ""
echo "Progress: [####################] 100%"
echo ""
echo "███    █    ███  ████  ████  █  █  ████  ███"
echo "█  █   █    █ █  █     █     █  █  █     █  "
echo "███    █    ███  ████  ████  ████  ████  ██ "
echo "█  █   █    █ █     █     █  █  █  █     █  "
echo "███    ███  ███  ████  ████  █  █  ████  ███"
echo ""
echo ""
echo "Screenshot ready! Press Print Screen key to capture this output."
echo ""
echo "This window will remain open for 15 seconds..."
sleep 15